### ISSUE TITLE
incorrect dependency type

### ISSUE THREAD

**Issue by chorny** [bmarcotte/Test-Subtest-Attribute#1]
Dist::Zilla::Plugin::* modules are listed as 'build' dependency in cpanfile. If they are not used in module installation, they should be listed as 'develop'. See https://metacpan.org/pod/CPAN::Meta::Spec#Phases

**Comment by bmarcotte** [comment]
Committed a fix for this in 00ad86274b43367dc790f8fcf427388549caad39, which was released in distro version 0.03.
